// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALN9S6RZ5aN3fzqgGpv-6Ki2cou7GJvFE',
    appId: '1:776875801756:web:adf292f96587c13b74c159',
    messagingSenderId: '776875801756',
    projectId: 'zentra-hub',
    authDomain: 'zentra-hub.firebaseapp.com',
    storageBucket: 'zentra-hub.firebasestorage.app',
    measurementId: 'G-EYW8V9980G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa4EV4it16UCn59wHP3d6W7ILPr1e8dbw',
    appId: '1:776875801756:android:dac0138f470010b374c159',
    messagingSenderId: '776875801756',
    projectId: 'zentra-hub',
    storageBucket: 'zentra-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpOedVIVhjdc_ED34sjE8laGoTjTo90pM',
    appId: '1:776875801756:ios:ca54538099e5161074c159',
    messagingSenderId: '776875801756',
    projectId: 'zentra-hub',
    storageBucket: 'zentra-hub.firebasestorage.app',
    iosClientId: '776875801756-152pi04dot4et273cn2tg4qnpcq4jdf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.zentra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpOedVIVhjdc_ED34sjE8laGoTjTo90pM',
    appId: '1:776875801756:ios:ca54538099e5161074c159',
    messagingSenderId: '776875801756',
    projectId: 'zentra-hub',
    storageBucket: 'zentra-hub.firebasestorage.app',
    iosClientId: '776875801756-152pi04dot4et273cn2tg4qnpcq4jdf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.zentra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALN9S6RZ5aN3fzqgGpv-6Ki2cou7GJvFE',
    appId: '1:776875801756:web:6c0634e563d771a074c159',
    messagingSenderId: '776875801756',
    projectId: 'zentra-hub',
    authDomain: 'zentra-hub.firebaseapp.com',
    storageBucket: 'zentra-hub.firebasestorage.app',
    measurementId: 'G-HYJWMLLJ03',
  );
}
